### ISSUE TITLE
install and use

### ISSUE THREAD

**Issue by JZZZ1314** [sail-sg/CLoT#4]
Can you provide a complete usage process? For example, the required dependency environment can be found in the published model weights related to qwen. How should we use this aspect

**Comment by zhongshsh** [comment]
No problem! Please refer to the usage guide at https://github.com/sail-sg/CLoT?tab=readme-ov-file#-quickstart.

**Comment by JZZZ1314** [comment]
PS D:\clot\CLoT\CLoT-cn>  d:; cd 'd:\clot\CLoT\CLoT-cn'; & 'c:\Users\orangecat\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\orangecat\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '56983' '--' 'd:\clot\CLoT\CLoT-cn\gradio_demo.py' 
Traceback (most recent call last):
  File "d:\clot\CLoT\CLoT-cn\gradio_demo.py", line 367, in <module>
    main()
  File "d:\clot\CLoT\CLoT-cn\gradio_demo.py", line 363, in main
    _launch_demo(args)
  File "d:\clot\CLoT\CLoT-cn\gradio_demo.py", line 112, in _launch_demo
    model, tokenizer = _load_model_tokenizer(args.checkpoint_path)
  File "d:\clot\CLoT\CLoT-cn\gradio_demo.py", line 63, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "c:\Users\orangecat\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 810, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "c:\Users\orangecat\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "c:\Users\orangecat\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\orangecat\.cache\huggingface\modules\transformers_modules\zhongshsh\CLoT-cn\20a6a772dc427b28dad422802321e14360fcbbc2\tokenization_qwen.py", line 140, in __init__
    self.mergeable_ranks = _load_tiktoken_bpe(vocab_file)  # type: dict[bytes, int]
  File "C:\Users\orangecat\.cache\huggingface\modules\transformers_modules\zhongshsh\CLoT-cn\20a6a772dc427b28dad422802321e14360fcbbc2\tokenization_qwen.py", line 54, in _load_tiktoken_bpe
    with open(tiktoken_bpe_file, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by zhongshsh** [comment]
https://github.com/QwenLM/Qwen/issues/361
